services:
  nats:
    image: docker.io/nats:latest
    ports:
      - 4222:4222
      - 8222:8222

  api-gateway:
    build:
      context: backend
      dockerfile: gateway/Dockerfile
    ports:
      - 3000:3000
    environment:
      NATS_HOST: nats://nats:4222
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: seasonalworkers
      KEYCLOAK_CLIENT_ID: mobile
      KEYCLOAK_CLIENT_SECRET: hgBSF3mCT0rHAFo8mmTHypb5eNWQMkok
    depends_on:
      - nats

  keycloak:
    image: bitnami/keycloak:22.0.5
    ports:
      - "8080:8080"
    env_file:
      - .env/keycloak.template.env
    command: ["kc.sh", "start-dev", "--import-realm"]
    volumes:
      - ./backend/keycloak/custom-theme:/opt/bitnami/keycloak/themes/custom/login
      - ./backend/keycloak/realm.json:/opt/bitnami/keycloak/data/import/realm.json
    depends_on:
      - db-keycloak

  db-keycloak:
    image: bitnami/postgresql:14
    env_file:
      - .env/postgres-keycloak.template.env
    volumes:
      - db_kc_data:/var/lib/postgres/data

  service-ad:
    build:
      context: backend
      dockerfile: services/ad/Dockerfile
    environment:
      - DB_HOST=db-service-ad
      - DB_PORT=5432
      - DB_USERNAME=ads
      - DB_PASSWORD=password
    depends_on:
      - nats
      - db-service-ad

  db-service-ad:
    image: postgres:14
    environment:
      - POSTGRES_USER=ads
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ads
    volumes:
      - db_service_ad_data:/var/lib/postgres/data

  # db-notifications:
  #   image: timescale/timescaledb:latest-pg15
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: notifications
  #   volumes:
  #     - db_notifications_data:/var/lib/postgresql/data

volumes:
  # db_notifications_data:
  db_kc_data:
  db_service_ad_data:
