services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    ports:
      - "8080:8080"
    env_file:
      - ./keycloack.env
    command: start-dev

  postgres-profile:
    image: postgres:latest
    container_name: postgres-seasonalworkers-profile
    env_file:
      - ./postgres-profile.env
    ports:
      - "5432:5432"
