spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: profile-route
          uri: lb://profile-service
          predicates:
            - Path=/workers/**
    management:
      endpoints:
        gateway:
          enabled: true
        web:
          exposure:
            include: gateway
server:
  port: 8090

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      hostname: localhost
