server:
  port: 8090

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/seasonnal
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: profile-route
          uri: lb://profile-service
          predicates:
            - Path=/workers/**

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      instance:
        prefer-ip-address: true
