export enum NatsSubjects {
  EXPERIENCE_CREATE = 'ADS.experiences.create',
  EXPERIENCE_FIND = 'ADS.experiences.find',
  EXPERIENCE_UPDATE = 'ADS.experiences.update',
  EXPERIENCE_REMOVE = 'ADS.experiences.remove',
  AVAILABILITY_CREATE = 'ADS.availabilities.create',
  AVAILABILITY_FIND = 'ADS.availabilities.find',
  AVAILABILITY_UPDATE = 'ADS.availabilities.update',
  AVAILABILITY_REMOVE = 'ADS.availabilities.remove',
  JOB_OFFERS_CREATE = 'ADS.jobs.create',
  JOB_OFFERS_RECOMMENDATION = 'ADS.jobs.recommendation',
  JOB_OFFERS_FIND_ONE = 'ADS.jobs.findOne',
  JOB_OFFERS_APPLY = 'ADS.jobs.apply',
  JOB_OFFERS_GET_STATUS = 'ADS.jobs.status',
  JOB_OFFERS_VALIDATION = 'ADS.jobs.validation',
  JOB_GET_CATEGORIES = 'ADS.jobs.categories',
  NOTIFICATIONS_JOBS_GET = 'NOTIFICATIONS.jobs.get',
}
