DROP TABLE IF EXISTS "workers";

CREATE TABLE IF NOT EXISTS "workers" (
    id  SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    fullname VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20) UNIQUE NOT NULL
);
