name: JAVA CI

on:
  workflow_call:
    inputs:
      directory:
        description: "Directory to change to"
        type: string
        required: true
jobs:
  checks:
    name: Java CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
